language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '9'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
# - chmod +x .travis/push.sh
#  - ./.travis/push.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install:
  - sudo apt-get install lua5.2
  - printf "registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - chmod +x .travis/test.sh
  - ./.travis/test.sh

#override npm ci for now
install: npm install
